# Generated by Django 5.0.4 on 2024-05-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prof_exp", models.TextField()),
                ("education", models.TextField()),
                ("skills", models.TextField()),
                ("certifications", models.TextField()),
            ],
        ),
    ]
